apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        orgId: 1
        type: loki
        access: proxy
        # Use the loki chart gateway service (stable endpoint for query/push paths)
        url: http://loki-gateway.monitoring.svc.cluster.local
        isDefault: false
        editable: false
