apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: loki-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: LOKI_S3_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: loki-s3-credentials
        property: accessKeyId
        metadataPolicy: None
    - secretKey: LOKI_S3_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: loki-s3-credentials
        property: secretKey
        metadataPolicy: None

