apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subsyncarr-plus-data
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
