apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  install:
    createNamespace: true
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  chart:
    spec:
      chart: metallb
      # pick a specific version you’re comfortable with; example:
      # version: 0.14.5
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  # values: {}   # usually you don’t need custom values; CRs below define IPs/BGP