# clusters/my-cluster/monitoring/bootstrap/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-metallb.yaml
  - helmrelease-metallb.yaml
  - ipaddresspool.yaml
  - l2advertisment.yaml