controllers:
  newtarr:
    replicas: 1

    containers:
      app:
        image:
          repository: ghcr.io/elfhosted/newtarr
          tag: v1.0.0
        env:
          TZ: Europe/London
        ports:
          - name: http
            containerPort: 9705
        probes:
          liveness:  { enabled: true, type: TCP, port: 9705 }
          readiness: { enabled: true, type: TCP, port: 9705 }

service:
  main:
    controller: newtarr
    ports:
      http:
        port: 9705
        targetPort: 9705
        protocol: TCP

ingress:
  main:
    enabled: true
    className: traefik-internal
    hosts:
      - host: newtarr.gregpakes.co.uk
        paths:
          - path: /
            service:
              identifier: main
              port: http

persistence:
  data:
    enabled: true
    existingClaim: newtarr-config
    globalMounts:
      - path: /config
