apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profilarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi    # <= must be <= PV capacity (5Gi here)
  volumeName: pvc-fa319d52-bb5f-4b31-9223-802f07fb28a7