apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntarr-config
  namespace: servarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn