apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-core
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision:  3.35.4
    helm:
      releaseName: argocd
      valueFiles: [values.yaml]
  syncPolicy:
    automated:
      selfHeal: true
      # IMPORTANT: don't enable prune yet; we’ll enable after adoption.
      # prune: true
    syncOptions:
      - CreateNamespace=true
      