apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshot-controller
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/kubernetes-csi/external-snapshotter
    targetRevision: v8.5.0
    path: deploy/kubernetes/snapshot-controller
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true