global:
  nodeSelector:
    longhorn: "true"
  tolerations:
    - key: dedicated
      operator: Equal
      value: longhorn
      effect: NoSchedule

engine:
  tolerations:
    - key: dedicated
      operator: Equal
      value: longhorn
      effect: NoSchedule
  nodeSelector:
    longhorn: "true"

longhornManager:
  nodeSelector:
    longhorn: "true"
  tolerations:
    - key: dedicated
      operator: Equal
      value: longhorn
      effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

longhornDriver:
  nodeSelector:
    longhorn: "true"
  tolerations:
    - key: dedicated
      operator: Equal
      value: longhorn
      effect: NoSchedule

csi:
  kubeletRootDir: /var/lib/kubelet
  attacher:
    updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
    nodeSelector: { longhorn: "true" }
    tolerations:
      - key: dedicated
        operator: Equal
        value: longhorn
        effect: NoSchedule
  provisioner:
    updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
    nodeSelector: { longhorn: "true" }
    tolerations:
      - key: dedicated
        operator: Equal
        value: longhorn
        effect: NoSchedule
  resizer:
    updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
    nodeSelector: { longhorn: "true" }
    tolerations:
      - key: dedicated
        operator: Equal
        value: longhorn
        effect: NoSchedule
  snapshotter:
    updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
    nodeSelector: { longhorn: "true" }
    tolerations:
      - key: dedicated
        operator: Equal
        value: longhorn
        effect: NoSchedule

# Reserve a bit of CPU so engines never starve during upgrades
guaranteedEngineCPU: 0.25

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  taintToleration: dedicated=longhorn:NoSchedule
  systemManagedComponentsNodeSelector: 'longhorn:true'
  defaultLonghornStaticStorageClass: longhorn
  backupTarget: cifs://172.16.250.191/Backups
  backupTargetCredentialSecret: longhorn-user-smb-backup-secret

persistence:
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack