{{- range .Values.pvcs }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ .backupName }}-src
  namespace: {{ .namespace }}
spec:
  sourcePVC: {{ .name }}
  trigger:
    schedule: {{ quote (default $.Values.restic.schedule .schedule) }}
  restic:
    repository: {{ $.Values.restic.repositorySecretName }}   # 👈 Secret name
    cacheCapacity: {{ $.Values.restic.cacheCapacity }}
    retain:
      daily: {{ $.Values.restic.retain.daily }}
      weekly: {{ $.Values.restic.retain.weekly }}
      monthly: {{ $.Values.restic.retain.monthly }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: {{ .backupName }}-restore
  namespace: {{ .namespace }}
spec:
  # No trigger.manual here - we patch it when we want to restore
  restic:
    repository: {{ $.Values.restic.repositorySecretName }}
    cacheCapacity: {{ $.Values.restic.cacheCapacity }}
{{- end }}