apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patchmon-secrets
  namespace: patchmon
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: patchmon-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
  data:
    - secretKey: postgres-password
      remoteRef:
        key: patchmon-secrets
        property: postgres-password
        nullBytePolicy: Ignore
    - secretKey: redis-password
      remoteRef:
        key: patchmon-secrets
        property: redis-password
        nullBytePolicy: Ignore
    - secretKey: jwt-secret
      remoteRef:
        key: patchmon-secrets
        property: jwt-secret
        nullBytePolicy: Ignore
    - secretKey: ai-encryption-key
      remoteRef:
        key: patchmon-secrets
        property: ai-encryption-key
        nullBytePolicy: Ignore
