# apps/nebula-sync/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-sync-config
  namespace: nebula-sync
data:
  # Scheduling & behavior (see README "Optional Environment Variables")
  TZ: "Europe/London"
  FULL_SYNC: "true"            # set "false" to use granular SYNC_* flags instead
  RUN_GRAVITY: "true"
  CRON: "0 * * * *"            # run hourly
  CLIENT_SKIP_TLS_VERIFICATION: "true" # Remove later
  # If you disable FULL_SYNC above, you can selectively turn on pieces, e.g.:
  # SYNC_GRAVITY_AD_LIST: "true"
  # SYNC_GRAVITY_DOMAIN_LIST: "true"
  # SYNC_GRAVITY_CLIENT: "true"
  # CLIENT_TIMEOUT_SECONDS: "60"
  # CLIENT_RETRY_DELAY_SECONDS: "5"
  # CLIENT_SKIP_TLS_VERIFICATION: "false"