# apps/nebula-sync/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace: nebula-sync
  labels:
    app.kubernetes.io/name: nebula-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nebula-sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nebula-sync
    spec:
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:v0.11.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nebula-sync-secrets
            - configMapRef:
                name: nebula-sync-config
          # The app runs continuously and triggers on CRON internally (per README)
          # Optional health endpoints: community reports indicate a health check on :8080
          # If your build exposes /healthz, these probes will work; otherwise remove them.
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"