apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik          # must match your existing release namespace
spec:
  interval: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    # Uncomment the next line to allow CRD upgrades (if chart supports it)
    crds: CreateReplace
  chart:
    spec:
      chart: traefik
      version: 37.1.2        # <-- set to the version you're on (or want)
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml