apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: homelab
spec:
  syncPolicy:
    automated: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        Homelab: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets