apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
  namespace: cloudflare-ddns
  annotations:
    # ensure this lands before the ClusterIssuer in the same child app
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: cloudflare-token-secret     # <-- same Secret name your ClusterIssuer references
    creationPolicy: Owner             # ESO will own (create/replace) the Secret
    deletionPolicy: Delete            # ESO will delete the Secret when the ExternalSecret is deleted
    template:
      type: Opaque
  data:
    - secretKey: cloudflare-token     # <-- key inside the k8s Secret (what cert-manager expects)
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: cloudflare-api-token     # <-- 1Password item title
        property: token               # <-- 1Password field name
        metadataPolicy: None
