controllers:
  flaresolverr:
    replicas: 1
    containers:
      app:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: latest
        env:
          TZ: "Europe/London"
          LOG_LEVEL: "info"
          CAPTCHA_SOLVER: "none"   # or 'hcaptcha-solver' if you add support later
          PORT: "8191"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  app:
    controller: flaresolverr
    type: ClusterIP
    ports:
      http:
        port: 8191

# Don’t declare ingress at all unless you really want it.
# If you DO want it, uncomment and fill in hosts.
# ingress:
#   app:
#     enabled: true
#     className: "traefik"
#     hosts:
#       - host: flaresolverr.yourdomain.local
#         paths:
#           - path: /
#             service:
#               name: app
#               port: http

# app-template v3 is picky about persistence, so we just don't define any.
# Flaresolverr is stateless, so this is fine.
persistence: {}

# Optionally, add probes if you want to use Aspire or Argo health checks
defaultProbes:
  enabled: true