controllers:
  flaresolverr:
    replicas: 1
    containers:
      app:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: latest
        env:
          TZ: "Europe/London"
          LOG_LEVEL: "info"
          CAPTCHA_SOLVER: "none"   # or 'hcaptcha-solver' if you add support later
          PORT: "8191"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  app:
    controller: flaresolverr
    type: ClusterIP
    ports:
      http:
        port: 8191

ingress:
  app:
    enabled: false
    # If you want to expose via Traefik, set to true and configure like this:
    # className: "traefik"
    # hosts:
    #   - host: flaresolverr.local.yourdomain.com
    #     paths:
    #       - path: /
    #         service:
    #           name: app
    #           port: http

persistence:
  # Flaresolverr doesn’t need persistent storage, but this block keeps Helm happy
  data:
    enabled: false

# Optionally, add probes if you want to use Aspire or Argo health checks
defaultProbes:
  enabled: true