apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn       # <-- your new Ceph StorageClass
  resources:
    requests:
      storage: 5Gi