apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-ceph
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd       # <-- your new Ceph StorageClass
  resources:
    requests:
      storage: 5Gi