apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi    # <= must be <= PV capacity (5Gi here)
  volumeName: pvc-bfa058fe-a44b-475b-a9bb-077505131843