apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-1ef61bb7-079b-424e-8251-9f1716588cc0