controllers:
  main:
    replicas: 1
    pod:
      securityContext:
        fsGroup: 988
        fsGroupChangePolicy: OnRootMismatch
    containers:
      radarr:
        image:
          repository: ghcr.io/linuxserver/radarr
          tag: latest
        env:
          TZ: Europe/London
          PUID: "1000"
          PGID: "988"
        ports:
          - name: http
            containerPort: 7878
            protocol: TCP

        probes:
          startup:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 7878
              initialDelaySeconds: 10
              periodSeconds: 5
              failureThreshold: 120   # up to ~10 minutes
          readiness:
            enabled: true
            type: TCP
            port: 7878
          liveness:
            enabled: true
            type: TCP
            port: 7878

service:
  web:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 7878
        targetPort: 7878

ingress:
  web:
    enabled: true
    className: traefik
    hosts:
      - host: radarr.gregpakes.co.uk
        paths:
          - path: /
            service:
              identifier: web
              port: http
    # tls: []  # add if you want certs now

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn

  downloads:
    enabled: true
    type: nfs
    server: 172.16.250.191
    path: /var/nfs/shared/Media

advancedMounts:
  main:
    radarr:
      - name: config
        path: /config
      - name: downloads
        path: /downloads