# apps/nebula-sync/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace: nebula-sync
  labels:
    app.kubernetes.io/name: nebula-sync
  annotations:
    argocd.argoproj.io/sync-wave: "5" # deploy after the external secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nebula-sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nebula-sync
    spec:
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:v0.11.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nebula-sync-secrets
            - configMapRef:
                name: nebula-sync-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"