# clusters/my-cluster/apps/longhorn/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-longhorn.yaml
  - helmrelease-longhorn.yaml
  - settings.yaml
