# clusters/my-cluster/apps/longhorn/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - settings.yaml
patches:
  - path: tolerations-patch.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system