apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system         # <- the Git source created by bootstrap
    namespace: flux-system
  path: ./clusters/my-cluster/apps/longhorn
  timeout: 3m
  wait: true