apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: taint-toleration
  namespace: longhorn-system
spec:
  value: dedicated=longhorn:NoSchedule
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: system-managed-components-node-selector
  namespace: longhorn-system
spec:
  value: '{"longhorn":"true"}'