apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  sources:

    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      chart: csi-driver-smb
      targetRevision: v1.15.0
      helm:
        releaseName: csi-driver-smb
        valueFiles:
          - $values/argocd/infrastructure/csi-driver-smb/values.yaml

    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      ref: values
      path: argocd/infrastructure/csi-driver-smb
      directory:
        recurse: true  