apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-stores
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"   # ESO -> 1Password -> stores -> app-secrets -> apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  source:
    repoURL: https://github.com/gregpakes/homelab
    targetRevision: main
    path: infrastructure/cluster-secret-store                                         # <— your current folder
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true