apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr

  sources:
    # 1) Upstream Homarr chart (non-OCI so it behaves like your bjw-s stuff)
    - repoURL: https://homarr-labs.github.io/charts
      chart: homarr
      targetRevision: 8.2.1
      helm:
        valueFiles:
          - $values/argocd/infrastructure/homarr/values.yaml

    # 2) Your repo – gives us BOTH the values (via ref) AND the manifests in that folder
    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      ref: values
      path: argocd/infrastructure/homarr
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true