apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://intel.github.io/helm-charts
    chart: intel-device-plugins-gpu
    targetRevision: "0.34.0"   # pin to a version later if you prefer
    helm:
      values: |
        nodeFeatureRule: false   # 👈 disables the NFD NodeFeatureRule object
        # Run on all nodes; it will only expose resources where GPUs exist.
        # If you want to limit to the GPU VM only, uncomment:
        # nodeSelector:
        #   kubernetes.io/hostname: k3s-06

        # Example: advertise full GPUs (default behaviour)
        # You generally don't need extra values here.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true