# apiVersion: v1
# kind: Pod
# metadata:
#   name: prometheus-migrate
#   namespace: monitoring
# spec:
#   restartPolicy: Never
#   containers:
#     - name: rsync
#       image: alpine:3.20
#       command: ["/bin/sh", "-c"]
#       args:
#         - |
#           echo "Installing rsync...";
#           apk add --no-cache rsync >/dev/null 2>&1;
#           echo "Starting rsync..."
#           rsync -avh /old/ /new/;
#           echo "Done. Sleeping so you can inspect..."
#           sleep 3600
#       volumeMounts:
#         - name: old-config
#           mountPath: /old
#         - name: new-config
#           mountPath: /new
#   volumes:
#     - name: old-config
#       persistentVolumeClaim:
#         claimName: prometheus-old-longhorn         # Longhorn PVC
#     - name: new-config
#       persistentVolumeClaim:
#         claimName: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0      # Ceph PVC

apiVersion: v1
kind: Pod
metadata:
  name: prometheus-debug
  namespace: monitoring
spec:
  containers:
    - name: shell
      image: alpine:3.20
      command: ["/bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: data
          mountPath: /prom
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0