# apiVersion: v1
# kind: Pod
# metadata:
#   name: bazarr-migrate
#   namespace: servarr
# spec:
#   restartPolicy: Never
#   containers:
#     - name: rsync
#       image: alpine:3.20
#       command: ["/bin/sh", "-c"]
#       args:
#         - |
#           echo "Installing rsync...";
#           apk add --no-cache rsync >/dev/null 2>&1;
#           echo "Starting rsync..."
#           rsync -avh /old/ /new/;
#           echo "Done. Sleeping so you can inspect..."
#           sleep 3600
#       volumeMounts:
#         - name: old-config
#           mountPath: /old
#         - name: new-config
#           mountPath: /new
#   volumes:
#     - name: old-config
#       persistentVolumeClaim:
#         claimName: bazarr-config           # Longhorn PVC
#     - name: new-config
#       persistentVolumeClaim:
#         claimName: bazarr-config-ceph      # Ceph PVC