apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator   # default; resources can override

  sources:
    # 1) MinIO Operator Helm chart
    - repoURL: https://operator.min.io/         # <- adjust if needed
      chart: operator
      targetRevision: 5.0.18                    # example, pin exact
      helm:
        releaseName: minio-operator
        valueFiles:
          - $values/argocd/infrastructure/minio-operator/values.yaml

    # 2) Your repo as values source
    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      ref: values

    # 3) Your extra manifests: tenant + secrets + namespaces
    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      path: argocd/infrastructure/minio-operator
      directory:
        recurse: true
        include: "*.yaml"
        exclude: "values.yaml"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - Replace=true