apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"   # after external-secrets + storage
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  sources:
    # 1) Upstream Helm chart (Bitnami MinIO)
    - repoURL: https://charts.bitnami.com/bitnami
      chart: minio
      targetRevision: 17.0.21
      helm:
        releaseName: minio
        valueFiles:
          - $values/argocd/infrastructure/minio/values.yaml

    # 2) Repo-local values + extra manifests (ExternalSecrets, etc.)
    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      ref: values
      path: argocd/infrastructure/minio
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
