apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer

  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      targetRevision: 4.6.2
      helm:
        valueFiles:
          - $values/argocd/infrastructure/portainer/values.yaml

    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      ref: values
      path: argocd/infrastructure/portainer
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
