apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    chart: rancher
    targetRevision: 2.12.x            # pin a version you want
    helm:
      values: |
        hostname: rancher.gregpakes.co.uk
        replicas: 2
        ingress:
          ingressClassName: traefik
        global:
          cattle:
            psp:
              enabled: false
        # bootstrapPassword: "TEMP-PASSWORD"   # optional
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true