apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restic-backups
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: backup-system
  source:
    repoURL: https://github.com/gregpakes/homelab
    targetRevision: main
    path: charts/restic-backups
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true