# monitoring/servicemonitor-pihole-exporter.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels: { app: pihole-exporter }
  namespaceSelector:
    matchNames: ["pihole"]
  endpoints:
    - port: http
      interval: 30s