# servarr/qbit-vpn/values.yaml
controllers:
  main:
    replicas: 1
    pod:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    containers:
      gluetun:
        image:
          repository: qmcgaw/gluetun
          tag: latest
        env:
          TZ: Europe/London
          VPN_SERVICE_PROVIDER: airvpn
          VPN_TYPE: wireguard
          WIREGUARD_PRIVATE_KEY:
            valueFrom: { secretKeyRef: { name: gluetun-secrets, key: WIREGUARD_PRIVATE_KEY } }
          WIREGUARD_PUBLIC_KEY:
            valueFrom: { secretKeyRef: { name: gluetun-secrets, key: WIREGUARD_PUBLIC_KEY } }
          WIREGUARD_PRESHARED_KEY:
            valueFrom: { secretKeyRef: { name: gluetun-secrets, key: WIREGUARD_PRESHARED_KEY } }
          WIREGUARD_ADDRESSES:
            valueFrom: { secretKeyRef: { name: gluetun-secrets, key: WIREGUARD_ADDRESSES } }
          FIREWALL: "on"
          HEALTH_VPN_DURATION_INITIAL: 120s
          HEALTH_TARGET_ADDRESS: "1.1.1.1:53"
          FIREWALL_INPUT_PORTS: "8080"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            add: ["NET_ADMIN"]
        mounts:
          - name: dev-tun
            path: /dev/net/tun

      qbittorrent:
        image:
          repository: ghcr.io/linuxserver/qbittorrent
          tag: latest
        env:
          TZ: Europe/London
          PUID: "1000"
          PGID: "1000"
          WEBUI_PORT: "8080"
          # Set the listening peer port in qBittorrent config
          QBT_BitTorrent__Session__Port:
            valueFrom: { secretKeyRef: { name: gluetun-secrets, key: FIREWALL_VPN_INPUT_PORTS } }
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: bt-tcp
            containerPort: 6881
            protocol: TCP
          - name: bt-udp
            containerPort: 6881
            protocol: UDP
        mounts:
          - name: config
            path: /config
          - name: downloads
            path: /downloads

service:
  webui:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8080
        targetPort: http
        protocol: TCP
  bittorrent:
    controller: main
    type: ClusterIP
    ports:
      tcp:
        port: 6881
        targetPort: bt-tcp
        protocol: TCP
      udp:
        port: 6881
        targetPort: bt-udp
        protocol: UDP

ingress:
  webui:
    enabled: true
    className: traefik
    hosts:
      - host: qbit.gregpakes.co.uk
        paths:
          - path: /
            service:
              identifier: webui
              port: http
    # tls: [...]   # optional

persistence:
  dev-tun:
    enabled: true
    type: hostPath
    hostPath: /dev/net/tun
    hostPathType: CharDevice

  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn

  downloads:
    enabled: true
    type: nfs
    server: 172.16.250.191
    path: /var/nfs/shared/Media