apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: backup-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: smb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username                 # 👈 key in the k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: backup-system                     # 1Password item title
        property: smb_username            # 1Password field name
        metadataPolicy: None
    - secretKey: password                 # 👈 key in the k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: backup-system                      # 1Password item title
        property: smb_password            # 1Password field name
        metadataPolicy: None
    # Optional domain support, if you have it in 1Password:
    # - secretKey: domain
    #   remoteRef:
    #     conversionStrategy: Default
    #     decodingStrategy: None
    #     key: pushover
    #     property: smb_domain
    #     metadataPolicy: None