apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-backup
provisioner: smb.csi.k8s.io
parameters:
  source: //172.16.250.191/Backups/k3sBackup
  csi.storage.k8s.io/node-stage-secret-name: smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: backup-system
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false