---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gregpakes # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: gregpakes-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.gregpakes.co.uk" # change to your domain
  dnsNames:
  - "*.gregpakes.co.uk" # change to your domain
  - gregpakes.co.uk # change to your domain