apiVersion: v1
kind: Secret
metadata:
  name: velero-minio-creds
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = velero-minio-admin
    aws_secret_access_key = super-secret-change-me