apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: velero-minio
  namespace: minio-tenant
spec:
  # New-style root credentials
  configuration:
    name: velero-minio-config

  # You can keep this or delete it; on newer operators it's not used for root creds
  # credsSecret:
  #   name: velero-minio-creds

  requestAutoCert: false
  mountPath: /export

  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: nfs-rwx
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Ti

  exposeServices:
    minio: true
    console: true