apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: minio-root-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: minio-root-credentials
        property: rootUser
        metadataPolicy: None
    - secretKey: rootPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: minio-root-credentials
        property: rootPassword
        metadataPolicy: None