apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-loki-user
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: minio-loki-user
    creationPolicy: Owner
  data:
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: loki-s3-credentials
        property: secretKey
        metadataPolicy: None

