apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-rbd-secret
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: csi-rbd-secret
    creationPolicy: Owner
    template:
      data:
        userID: admin
        userKey: "{{ .ceph_admin_secret }}"
  data:
    - secretKey: ceph_admin_secret
      remoteRef:
        key: ceph-admin-secret
        property: ceph-admin-secret