apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuer
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/apps/cert-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager       # <-- ensures CRDs exist before dry-run
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager  # <-- wait until webhook is Ready
  timeout: 10m