apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/apps/cert-manager              # <-- path in your repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system                    # bootstrap name (adjust if different)
  timeout: 5m