apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-settings
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/my-cluster/apps/longhorn/settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: longhorn