apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/apps/pihole          # <- your pihole folder
  prune: true
  dependsOn:
    - name: traefik             # <- THIS ensures CRDs exist before dry-run/apply
  sourceRef:
    kind: GitRepository
    name: flux-system