# flux-kustomization.yaml  (in flux-system or your mgmt repo)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rancher-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/apps/rancher       # <-- folder containing the YAMLs above
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager      # if you manage cert-manager via its own Kustomization