apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/apps/traefik          # <- path to your traefik folder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system