apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-1password-secret
  namespace: openclaw
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    name: openclaw-1password-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: openclaw
        property: op-connect-token
        metadataPolicy: None
